#+TITLE: MANUAL VDC603
#+AUTHOR: Calin Capitanu

* Poza 1

VDC-603 este parte din sistemul de masurare (Calibrator de doza radionuclida)
care este folosit sa masoare activitatea radioactiva a unei surse. VDC-603 are functia de 
sistem de a citi si de a controla. Un factor izotop al listei de nuclizi
in VDC 603 poate fi trimis la camera de ionizare din meniu. Partea de detectare a compartimentului
de ionizare este reprezentatea de un compartiment cu gaz in forma circulara de "U", cunoscut si 
ca "Well type chamber" (Compartimentul tipului bun). Mai multe configuratii cu compartimente
de ionizare sunt posibile. O unitatea de citire si control VDC-603 cu un compartiment de
ionizare VIK-202 va forma un calibrator de doza VDC-603, o unitate de citire si control  
VDC-603 cu compartiment de ionizare VIK-203 va forma un calibrator de doza VDC-603XR.

Cand o cerere de date este trimisa de unitatea de citire si control VDC-603, compartimentul de ionizare
masoare, transforma si returneaza activitatea masurata catre VDC-603 cu setarile de nuclid furnizate.
Unitatea de citire si control a sistemului are grija de selectia nuclidului si de functia de afisare a activitatii.
Puterea (5 VDC) pentru procesarea semnalului electronicelor in compartimentul de ionizare este
data de cablul de date.

* Poza 2

Sistemul va afisa numele producatorului atunci cand porneste, versiunea firmware-ului VDC-603 si versiunea firmwareului
compartimentului de ionizare. O cerere de conectare a compartimentului de ionizare este afisata daca compartimentul de
ionizare nu este conectat sau nu este conectat cum trebuie. Secventa de pornire continua cand comparimentul de ionizare
este conectat cum trebuie.

Dat fiind faptul ca este necesar ca compartimentul de ionizare sa fie stabil astfel incat masuratorile sa fie 
precise, este recomandat sa lasati VDC-603 si compartimentul de ionizare pornite mereu. Din acest motiv, sistemul de
calibrare a dozelor VDC-603 poate sa fie stins doar prin scoaterea din priza a acestuia.

* Poza 3



