#+TITLE: MANUAL VDC603
#+AUTHOR: Calin Capitanu

* Poza 1

VDC-603 este parte din sistemul de masurare (Calibrator de doza radionuclida)
care este folosit sa masoare activitatea radioactiva a unei surse. VDC-603 are functia de 
sistem de a citi si de a controla. Un factor izotop al listei de nuclizi
in VDC 603 poate fi trimis la camera de ionizare din meniu. Partea de detectare a compartimentului
de ionizare este reprezentatea de un compartiment cu gaz in forma circulara de "U", cunoscut si 
ca "Well type chamber" (Compartimentul tipului bun). Mai multe configuratii cu compartimente
de ionizare sunt posibile. O unitatea de citire si control VDC-603 cu un compartiment de
ionizare VIK-202 va forma un calibrator de doza VDC-603, o unitate de citire si control  
VDC-603 cu compartiment de ionizare VIK-203 va forma un calibrator de doza VDC-603XR.

Cand o cerere de date este trimisa de unitatea de citire si control VDC-603, compartimentul de ionizare
masoare, transforma si returneaza activitatea masurata catre VDC-603 cu setarile de nuclid furnizate.
Unitatea de citire si control a sistemului are grija de selectia nuclidului si de functia de afisare a activitatii.
Puterea (5 VDC) pentru procesarea semnalului electronicelor in compartimentul de ionizare este
data de cablul de date.

* Poza 2

Sistemul va afisa numele producatorului atunci cand porneste, versiunea firmware-ului VDC-603 si versiunea firmwareului
compartimentului de ionizare. O cerere de conectare a compartimentului de ionizare este afisata daca compartimentul de
ionizare nu este conectat sau nu este conectat cum trebuie. Secventa de pornire continua cand comparimentul de ionizare
este conectat cum trebuie.

Dat fiind faptul ca este necesar ca compartimentul de ionizare sa fie stabil astfel incat masuratorile sa fie 
precise, este recomandat sa lasati VDC-603 si compartimentul de ionizare pornite mereu. Din acest motiv, sistemul de
calibrare a dozelor VDC-603 poate sa fie stins doar prin scoaterea din priza a acestuia.

* Poza 3

- Tastele de navigatie

  Doua taste indicate prin simbolurile "sus" si "jos" (sageti) sunt folosite pentru a derula prin meniuri si pentru a 
modifica valori.

- Tasta OK

  Tasta OK este folosita pentru a intra in meniul utilizatorului atunci cand VDC-603 afiseaza ecranul de masura. 
Aceasta tasta este folosita si pentru a intra in sau executa elemente din meniu, pentru a confirma editarea 
valorilor si pentru a selecta elemente dintr-o lista, de exemplu: un nuclid de masurat, o limba sau o unitate
de masura.

5.2 Editarea valorilor numerice

Daca editarea valorilor sau introducerea unei parole este necesara, prima cifra a acestei valori va incepe sa clipeasca
pe ecran. Este posibil sa editezi aceasta cifra prin folosirea tastelor de navigatie (alea cu sageti in sus si in jos).
Daca o cifra are valoarea corecta, puteti confirma acest lucru prin apasarea tastei OK, iar urmatoarea cifra se va
selecta automat. Daca ultima cifra este confirmata cu tasta OK, intreaga valoare va fi confirmata.

* Poza 4

5.3 Ecranul de masurare

Ecranul standard de afisare este ecranul de masurare. Dupa o pornire reusita a VDC-603, acesta va afisa ecranul de
masurare si va actualiza masuratoarea activitatii la fiecare 2 secunde. Ecranul de masurare este independent de 
limba si este compus din 3 zone in care urmatarele proprietati sunt afisate:

1. Activitatea
2. Unitatea de masurare
3. Izotopul selectat

Este important ca izotopul selectat sa fie acelasi cu cel masurat. Unitatile de masura sunt selectabile din
meniul utilizatorului, astfel incat sa fie fie Becquerel (mod implicit - asa e in mod normal) sau Curie.
Scalarea la kBq, MBq sau GBq este facuta automat, depinzand de activitatea masurata.

Marginile in care aceste unitati sunt folosite sunt:
<poza nu se vede mai departe>

* Poza 5

5.4 Structura meniurile

5.4.1 Meniul operator

Meniul operator al VDC-603 este acesibil prin apasarea tastei OK in timp ce ecranul de masurare este prezent (afisat).
Masuratoarea activitati va inceta, meniul operator se deschide si prima intrare a meniului va fi afisata. Este posibil
sa derulezi prin meniu apasand pe tastele de navigatie (sagetile in sus si in jos). O element al meniului poate fi
accesat prin apasarea tastei OK.

Structura meniului operator:

1. SELECTEAZA IZOTOP
2. EXECUTA ZERO
3. SETEAZA INTERFATA
4. VERIFICA HV
5. UNITATE
6. LIMBA
7. AFISEAZA PARAMETRII
8. ECONOMISIRE ENERGIE
9. IESI DIN MENIU

Dupa executarea unui element din meniu, VDC-603 se va intoarce la ecranul de masurare. Ultimul element al meniului este 'EXIT MENU',
iar acesta va iesi din meniul operator si se va intoarce la ecranul de masurare. VDC-603 va iesi automat din meniul operator atunci
cand nicio tasta nu este apasata pentru 15 secunde.

* Poza 6

